/**
 * One-shot importer: pulls the point-marker layers from the Esencial Costa Rica
 * interactive map's `map-data.js` and emits `src/data/costaRica.ts` as typed
 * `Place[]`. Coordinates/names/descriptions are reused as reference data.
 *
 * Run:  node scripts/import-ecr.mjs
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const SRC_URL = "https://www.esencialcostarica.com/mapainteractivo/map-data.js";

// Source layer key -> our Category. Only point-marker layers are imported.
const LAYER_TO_CATEGORY = {
  volcanes: "volcano",
  cerros: "peak",
  parques: "park",
  faunaTerrestre: "wildlife",
  cataratas: "waterfall",
  bosques: "forest",
  hitos: "landmark",
  datos: "funFact",
  aeropuertos: "airport",
  puertos: "port",
  fauna: "marineWildlife",
  hitosOceanicos: "oceanMilestone",
  islas: "island",
};

const src = await (await fetch(SRC_URL, { headers: { "User-Agent": "Mozilla/5.0" } })).text();
// The file is `const MAP_DATA = {...}`. Evaluate it and hand the object back.
const MAP_DATA = new Function(`${src}\n;return MAP_DATA;`)();

const places = [];
const counts = {};
for (const [layer, category] of Object.entries(LAYER_TO_CATEGORY)) {
  const items = MAP_DATA[layer];
  if (!Array.isArray(items)) continue;
  let n = 0;
  items.forEach((it, i) => {
    let lat = it.lat;
    let lng = it.lng;
    let boundary;
    // Some layers (e.g. forests) store a polygon ring instead of a point;
    // place the marker at the ring's centroid and keep the ring as a boundary.
    if ((typeof lat !== "number" || typeof lng !== "number") && Array.isArray(it.coords) && it.coords.length) {
      const sum = it.coords.reduce((acc, [la, ln]) => [acc[0] + la, acc[1] + ln], [0, 0]);
      lat = sum[0] / it.coords.length;
      lng = sum[1] / it.coords.length;
      boundary = it.coords;
    }
    if (typeof lat !== "number" || typeof lng !== "number") return;
    const meta = it.alt || it.area || undefined;
    places.push({
      id: `ecr-${layer}-${i}`,
      name: it.name,
      description: it.desc ?? "",
      category,
      latitude: lat,
      longitude: lng,
      ...(meta ? { meta } : {}),
      ...(boundary ? { boundary } : {}),
      createdAt: "2024-01-01T00:00:00.000Z",
    });
    n++;
  });
  counts[layer] = n;
}

const banner =
  "// AUTO-GENERATED by scripts/import-ecr.mjs — do not edit by hand.\n" +
  "// Reference points from the Esencial Costa Rica interactive map\n" +
  `// (${SRC_URL}). Regenerate with: node scripts/import-ecr.mjs\n`;
const body = `import type { Place } from "../types/place";\n\nexport const COSTA_RICA_PLACES: Place[] = ${JSON.stringify(
  places,
  null,
  2,
)};\n`;

const dataDir = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "data");
writeFileSync(join(dataDir, "costaRica.ts"), banner + "\n" + body);

// ---- Line/boundary overlay layers (rivers + national border) ----------------
const rivers = (Array.isArray(MAP_DATA.rios) ? MAP_DATA.rios : [])
  .filter((r) => Array.isArray(r.coords) && r.coords.length > 1)
  .map((r) => ({ name: r.name, coords: r.coords }));

const border = [MAP_DATA.crBorderNicaragua, MAP_DATA.crBorderPanama]
  .filter((seg) => Array.isArray(seg) && seg.length > 1);

const overlaysBody =
  `import type { Localized } from "../types/place";\n\n` +
  `export interface GeoLine {\n  name: Localized;\n  coords: [number, number][];\n}\n\n` +
  `export const RIVERS: GeoLine[] = ${JSON.stringify(rivers, null, 2)};\n\n` +
  `/** National land border, as separate polyline segments. */\n` +
  `export const NATIONAL_BORDER: [number, number][][] = ${JSON.stringify(border, null, 2)};\n`;
writeFileSync(join(dataDir, "overlays.ts"), banner + "\n" + overlaysBody);

console.log(`Wrote ${places.length} places to src/data/costaRica.ts`);
console.log(`Wrote ${rivers.length} rivers, ${border.length} border segments to src/data/overlays.ts`);
console.table(counts);
